# Alembic Configuration

# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default revision_id
# is used to determine the name and ordering of the files.
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to be to datetime.tz module. leave blank
# for localtime
# timezone =

# max length of characters to apply to the
# "slug" field when generating a new migration
# unused by default and overridden in env.py when using --autogenerate
# truncate_slug_len = 40

# Set the sqlalchemy.url value in the environment rather than in here
# to get a copy of your database structure for development/testing
sqlalchemy.url = sqlite:///chere.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
