services:
  - type: web
    name: chere-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: development
      - key: SECRET_KEY
        generateValue: true
