"""Add PWA models

Revision ID: c561f3c4ac7b
Revises: add_event_system
Create Date: 2026-07-23 11:17:11.364250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c561f3c4ac7b'
down_revision = 'add_event_system'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwa_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('popup_delay', sa.Integer(), nullable=True),
    sa.Column('dismiss_duration_days', sa.Integer(), nullable=True),
    sa.Column('custom_title', sa.String(length=200), nullable=True),
    sa.Column('custom_description', sa.String(length=300), nullable=True),
    sa.Column('custom_button', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('install_requested', sa.Boolean(), nullable=True),
    sa.Column('install_completed', sa.Boolean(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_installations_created_at'), 'app_installations', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_installations_user_id'), 'app_installations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_installations_user_id'), table_name='app_installations')
    op.drop_index(op.f('ix_app_installations_created_at'), table_name='app_installations')
    op.drop_table('app_installations')
    op.drop_table('pwa_config')
    # ### end Alembic commands ###
